# Generated by Django 4.0.5 on 2022-07-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='User_from',
            new_name='Username',
        ),
    ]
