# Generated by Django 4.0.5 on 2022-07-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_from_appointment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='offhours_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='offhours_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
